In [3]:
import numpy as np


In [5]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [1]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [2]:
import numpy as np
TwoD_arr=np.arange(10).reshape(2,5)
TwoD_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
import numpy as np
TwoD_arr=np.arange(10).reshape(2,5)
TwoD_arr
print(TwoD_arr[0:,3:4])

[[3]
 [8]]


In [1]:
import numpy as np
Arr = np.random.randint(5, size=(10,10))
Arr

array([[4, 2, 1, 4, 3, 0, 0, 4, 1, 0],
       [3, 2, 2, 2, 0, 3, 3, 0, 3, 2],
       [4, 2, 4, 0, 1, 3, 3, 3, 3, 4],
       [3, 3, 4, 2, 1, 2, 3, 3, 1, 4],
       [1, 0, 0, 4, 0, 4, 2, 0, 1, 3],
       [4, 0, 1, 1, 0, 0, 0, 4, 2, 1],
       [4, 0, 3, 1, 0, 0, 2, 2, 2, 1],
       [1, 0, 2, 0, 2, 2, 0, 2, 1, 4],
       [0, 0, 0, 2, 3, 2, 2, 0, 2, 1],
       [4, 2, 3, 0, 0, 0, 0, 1, 1, 0]])

In [2]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.intersect1d(a,b)
c


array([2, 4])

In [3]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))


[2 4]


In [10]:
d = np.random.randn(7, 4)
d


array([[ 1.56694415,  0.11210044, -0.28995066, -0.36959482],
       [-0.17676275, -0.75074908,  0.92135276,  1.39982636],
       [ 0.23665501, -0.25324838, -0.11858238,  0.81039009],
       [ 0.19871493,  0.79683181,  0.18910218,  0.13401423],
       [-1.33033164, -1.25581959, -0.39517163,  0.35683932],
       [-0.82444769, -0.44064821,  0.26952822, -1.84811099],
       [-1.41986174, -1.05869334,  1.96317103,  0.23496713]])

In [4]:
import numpy as np

ThreeD_arr=np.arange(1,17).reshape(2,2,4)

ThreeD_arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [5]:
ThreeD_arr
np.swapaxes(ThreeD_arr,0,1)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

In [8]:
ThreeD_arr=np.arange(1,17).reshape(2,2,4)

ThreeD_arr


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [9]:
ThreeD_arr.T


array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

In [ ]:
#set vs unique

In [10]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names= set(names)
names


{'Bob', 'Joe', 'Will'}

In [12]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique_arr= np.unique(names)
unique_arr

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [ ]:
#Find the set difference of two arrays.

#Return the unique values in ar1 that are not in ar2.



In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
print(result)


In [13]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
multpli=np.matmul(x, y)
multpli

array([[ 28.,  64.],
       [ 67., 181.]])

In [17]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
c = x.dot(y)
c


array([[ 28.,  64.],
       [ 67., 181.]])